[workspace]
authors = ["Joris <gentinetta.joris@gmail.com>"]
channels = ["conda-forge"]
name = "biomech_PCP"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.8,<3.9"
pybullet = ">=3.25,<4"


[pypi-dependencies]
biomech_pcp = { path = ".", editable = true }
dynamics = { path = "./dynamics", editable = true }

mediapipe = ">=0.10.11, <0.11"
opencv-python = ">=4.12.0.88, <5"
imageio = { version = ">=2.35.1, <3", extras = ["ffmpeg"] }
numpy = ">=1.24.4, <2"
pandas = ">=2.0.3, <3"
pyarrow = ">=17.0.0, <18"
zmq = ">=0.0.0, <0.0.1"
matplotlib = ">=3.7.5, <4"
scikit-learn = ">=1.3.2, <2"
tqdm = ">=4.67.1, <5"
torch = ">=2.4.1, <3"
wandb = ">=0.21.1, <0.22"
pyserial = ">=3.5, <4"
pyqt5 = ">=5.15.11, <6"
pyqtgraph = ">=0.13.3, <0.14"
pyzmq = ">=27.0.1, <28"
scipy = ">=1.10.1, <2"
pillow = ">=10.4.0, <11"
pyyaml = ">=6.0.2, <7"
wget = ">=3.2, <4"
ruff = ">=0.12.8, <0.13"
